### ISSUE TITLE
Discussion: situation with versions

### ISSUE THREAD

**Issue by airways** [imgui-rs/imgui-rs#663]
Hi there everyone. Hopefully discussion tickets are allowed on this project.

I would really like to contribute to this project as I am gearing up to hopefully do a bunch of work on top of it, so I would love to discuss this and figure out the best way to make this repo easier for people to use.

Currently it is quite hard to actually get remote crates.io based dependencies working for a new project. I have only been successful using the latest head of `main` in a local directory with dependencies like this:

`myproject/Cargo.toml`
```toml
[package]
name = "myproject"
version = "0.1.0"
authors = ["Isaac Raway <github.com/airways>"]
edition = "2018"
publish = false

[dependencies]
clipboard = "0.5"
glium = { version = "0.31", default-features = true }
image = "0.23"
imgui = { path = "../imgui-rs/imgui", features = ["tables-api"] }
imgui-glium-renderer = { path = "../imgui-rs/imgui-glium-renderer" }
imgui-winit-support = { path = "../imgui-rs/imgui-winit-support" }
```

For clarity the directory tree looks like this:
```
├───imgui-rs
│   ├───docs
│   ├───imgui
│   ├───imgui-examples
│   ├───imgui-glium-renderer
│   ├───imgui-glow-renderer
│   ├───imgui-sdl2-support
│   ├───imgui-sys
│   ├───imgui-winit-support
│   ├───resources
│   ├───target
│   └───xtask
│       └───src
└───myproject
    ├───src
    └───target
```

So, I have the following questions/discussion points:

1. Currently the `main` branch is tagged with `imgui` version `0.8.1-alpha.0`.
2. Is this actually `0.8.3-alpha.0` effectively?
3. Do you use a branching strategy such as [Git Flow](https://datasift.github.io/gitflow/IntroducingGitFlow.html) or some other one? Would it be possible to maintain main as the stable latest version, with development branches for each planned version branched off of that and kept separate until ready for release?
    * Features would of course remain in their own forks/branches, and could be merged to different release branches if something needs to be delayed to a later release, etc.
    * Would not want to be making direct commits to main or release branches to ensure that main is stable and releases can be re-built as needed if a feature is backed out.
    * I think this would help make it clear what is WIP and what is stable by keeping things separate.
    * I think _maybe_ this is kind of already the case with 0.8.2-patch which looks like something of a release branch for `0.8.3` maybe, though this is confusing due to the branch name and the version of `imgui` in `main`. The history of that branch and discussions about it are pretty hard for me to grok.
4. Does anyone have a separate repo with a template project using `glium + imgui-glium-renderer + imgui-winit-support` from crates.io that works today (2022-08-27)? Separate repo seems important to ensure no unusual dependencies on this repo, which is what makes the examples here hard to translate due to missing Cargo files, version mismatches, etc.
7. Does anyone have a template like this also containing all of the currently working addon crates?

I also do want to say thank you to everyone who has worked on this package, it is really excellent to have something like this available for Rust.

IJR
