### ISSUE TITLE
App shows a blank window on start

### ISSUE THREAD

**Issue by ghostman2013** [imgui-rs/imgui-rs#750]
**Description**
I copied a code from an example: [Hello, World!](https://github.com/imgui-rs/imgui-rs/blob/main/imgui-examples/examples/hello_world.rs).
It's a total duplicate, project dependencies below:

```toml
[dependencies]
copypasta = "0.10.0"
glium = { version = "0.32.1", default-features = true }
imgui = { version = "0.11.0", features = ["freetype"] }
imgui-glium-renderer = "0.11.0"
imgui-winit-support = "0.11.0"
# Pin indirect dependency scoped-tls to 1.0.0
# as 1.0.1 bumped MSRV to 1.59
# Used only in
# imgui-examples -> glium -> glutin -> wayland-client -> scoped-tls
# so not worth bumping MSRV for this basically to keep CI happy
# FIXME: Remove this for imgui-rs v0.10 and bump MSRV
scoped-tls = "=1.0.0"
```

However, when I launch app it shows a blank window. If I resize the window at least a bit GUI begins showing well. 

I have also tried to move a mouse pointer over this blank window and... It works! I mean the mouse cursor is changed like there are GUI controls under it. Everything works just invisible until you won't resize the window.

**To Reproduce**

1. Run app
2. Watch a blank window =)

**Expected behavior**
1. Run app
2. Watch an awesome ImGUI

**Screenshots**
Before resizing
<img width="1136" alt="Screenshot 2023-11-05 at 02 03 36" src="https://github.com/imgui-rs/imgui-rs/assets/5940856/51d347f9-8029-4672-be84-b889f1d814a7">
After resizing
<img width="905" alt="Screenshot 2023-11-05 at 02 03 47" src="https://github.com/imgui-rs/imgui-rs/assets/5940856/1a69ebee-44e3-45ed-b6f0-387c33279c8a">

**Please describe your environment**
I use macOS (M1 Pro, Sonoma 14.2), rustc 1.75.0-nightly (a2f5f9691 2023-11-02)

**Other information**
If it's required I will provide any additional details about this bug
