### ISSUE TITLE
Splitting the Repository Up

### ISSUE THREAD

**Issue by sanbox-irl** [imgui-rs/imgui-rs#780]
This repository has a few crates inside it: `imgui`; `glium` and `glow` renderers; and `sdl2` and `winit` platform support.

I propose here that we should move all the crates which *aren't* `imgui` out of here.

There are a few reasons for this, but first and foremost, it will make imgui significantly easier to maintain. Although it is perfectly reasonable to update `imgui` without updating other platform dependencies, in practice, things tends to all go at once. It would be nice for `imgui` updates to not necessarily depend so much on the platforms.

Secondarily, it will simplify issue creation tremendously. Users won't be reporting to an omni-repository, but rather, to individual repositories.

We can see that in `imgui-wgpu`, which is a successful example we should follow.

What do you all think?

**Comment by dbr** [comment]
I'm in favour of this.

Part of this is we should decouple the versions of imgui-rs and the support/renderer modules (their release cycles should be independent - e.g the winit changes didn't necessitate any change in imgui-rs itself). We could do within the same monorepo approach, but as you say there's other organization benefits to having them as separate repos

Another (rare) benefit would be deprecating repos like happened with [gfx](https://github.com/imgui-rs/imgui-gfx-renderer) - if they are separate repos, they can just be wrapped up and archived, whereas currently we have to move the code elsewhere (which is a bit more work)

It also would make it "cleaner" if someone was to take over maintenance of a specific renderer-integration, and if was value/interest in moving imgui-wgpu-rs etc into the imgui-rs org

The only downside I can think of is the examples - since they rely on a renderer, they also either need to move to a separate repo (which makes keeping them in sync a tiny bit harder), or have a weird circular dependency. However practically I think having them in a separate repo would work okay - there shouldn't be a huge amount of churn in those examples

I think @thomcc was a big proponent for the monorepo approach - he may have some opinions (or not, as he's very busy with other things!)

**Comment by sanbox-irl** [comment]
Exactly -- @dbr , I don't know about you, but I actually use none of our integrations personally -- my projects at work use their own integrations, since it tends to be easier. These repositories should have maintainers who are more personally invested in them, whereas my interest is in `imgui` itself! To continue to use the `imgui-wgpu` repository as an example, it was started by wgpu affiliated folks primarily. I think having many of our repositories have more support from the relevant platforms would be ideal -- in practice, we don't really use very many platform specific features, it's more just the types tend to come out platform particular

**Comment by juliusl** [comment]
I think it's a good plan but there is one issue that I've been running into when trying to go between versions of imgui-rs. 

Since imgui-sys sets the `links` property in the `Cargo.toml`, when compiling a dependency that has a dependency on imgui-rs, cargo ends up breaking. Which means that if you pull one dependency using imgui-rs, all dependencies using imgui-rs have to use the same version. I've managed to get SxS imgui-rs working (for example 11 and 12 in the same project behind feature flags) but I had to fork the repo, rename imgui to imgui_xx and then change all the dependents to reference the _xx version (including imgui-wgpu).

I'm not sure what a solution would look like or how to address this problem but I think it would support the goal of making imgui-rs is easier to maintain.

**Comment by sanbox-irl** [comment]
ahh @juliusl good point. I think leaving `imgui` and `imgui-sys` in the same repository is very sensible. supporting having two different imgui-rses does sound very challenging and niche to me, so accepting that hard requirement seems fine

**Comment by juliusl** [comment]
> supporting having two different imgui-rses

It's not necessarily about having two different imgui-rses (and I think for the most part this might get solved w/ the repo split) and more about the dependencies outside of imgui-rs. Say for example you need a more recent version of winit or wgpu. 

Since both these libraries have a history of having breaking changes between apis, it's helpful to feature-flag them while other dependencies catch up and while they take time to stabalize. 

If you're on an older version of imgui-rs/imgui-rs-winit that means you might need an updated version so that you can test these changes with but you can't nesscarilly move forward w/ _all_ your dependencies yet so you want to feature-flag the updated stack. 

So for example something like this: 

```toml
imgui12 = { package = "imgui", version = "0.12.0", optional = true }
imgui11 = { package = "imgui", version = "0.11.0", optional = true }

imgui_winit_support_12 = { package = "imgui-winit-support", version = "0.12.0", optional = true }
imgui_winit_support_11 = { package = "imgui-winit-support", version = "0.11.0", optional = true }

winit29 = { package = "winit", version = "0.29.0", optional = true }
winit27 = { package = "winit", version = "0.27.0", optional = true }

[features] 
stable = [ "dep:imgui11", "dep:imgui_winit_support_11", "dep:winit27" ]
vnext = [ "dep:imgui12", "dep:imgui_winit_support_12", "dep:winit29" ] 
```

The problem is that cargo only lets you link one version of a crate at a time, so the above will fail to compile even if you're **not** even referencing both versions at the same time. Just because the second version is in the manifest at all will cause cargo to fail. The only solution I've found that doesn't fracture my repo was to rename the package name of the later version of imgui to imgui_xx and than cargo is happy again.

This is friction being caused by cargo and not anything imgui-rs is doing wrong (I think the openssl based crates have run into this before as well).

Not trying to push for a solution, but I just wanted to call out a realistic complication I'm running into downstream.
